### ISSUE TITLE
Tried to translate "mi citmau do la nanca be li xa"

### ISSUE THREAD

**Issue by dinynaus** [lojban/jbofihe#14] opened 2020-12-04 21:52 UTC
Error:
An unexpected error has occurred whilst running jbofihe.

Please submit a report on https://github.com/lojban/jbofihe/issues
with at least these pieces of information:
  Version of jbofihe (jbofihe -v)
  Command line options
  The input text

Version:
jbofihe version 0.42

CLI Options:
jbofihe -x tst.txt
(tst.txt is where the phrase is located. There is no other text in the file and attempts to translate through the website, http://lojban.org/jboski/index.php, yielded the same results.)

Input Text:
mi citmau do la nanca be li xa
(Example 12.88 from https://lojban.pw/cll/uncll-1.2.8.1/xhtml_section_chunks/section-comparatives.html)

**Comment by mezohe** [comment] 2020-12-05 14:24
This is the same bug as #5 and #8. It's been known for at least seven years, and nobody active in that time has known jbofihe well enough to fix it. You could try contacting the original author, https://github.com/rc0 .

**Comment by lagleki** [comment] 2020-12-05 14:28
Duplicate of #5

**Closed by lagleki** 2020-12-05 14:28 UTC
